baseURL: "https://cfe.dev/"
languageCode: "en-us"
title: "Certified Fresh Events"
params:
  description: "Certified Fresh Events LLC specializes in creating and organizing events around technology, development/programming and IT."
  twitter: fresheventsfl
  instagram: certifiedfreshevents
  youtube: https://www.youtube.com/channel/UC8mBtfX_7KNLP3LMQZJA8yg
menu: ["main", "top"]
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: categories
    weight: 100
  - name: date
    weight: 10
paginate: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true