baseURL: "https://redesign.cfe.dev/"
languageCode: "en-us"
title: "CFE.dev"
params:
  description: >-
    CFE.dev offers a large library of recorded sessions on a wide range of development
    & technology topics live & interactive virtual meetups featuring the experts.
  twitter: fresheventsfl
  instagram: certifiedfreshevents
  youtube: https://www.youtube.com/channel/UC8mBtfX_7KNLP3LMQZJA8yg
  featured_categories:
    - javascript
    - culture
    - iot
    - serverless
menu: ["main", "top"]
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: categories
    weight: 100
  - name: date
    weight: 10
paginate: 6

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - Algolia
  page:
    - HTML
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
params:
  algolia:
    vars:
      - title
      - summary
      - date
      - permalink
      - description
    params:
      - categories
