baseURL: "https://cfe.dev/"
languageCode: "en-us"
title: "Certified Fresh Events"
params:
  description: "Certified Fresh Events LLC specializes in creating and organizing events around technology, development/programming and IT."
menu: ["main", "top"]