name = "cfe-2020"
license = ""
licenselink = ""
description = "Website for CFE.dev"
homepage = "https://github.com/remotesynth/certifiedfreshevents/"
tags = []
features = []
min_version = "0.73.0"

[author]
  name = "YupGup, LLC"
  homepage = "https://yupgup.com"
